(()=>{
  'use strict';
  const SEEN_BUILD_KEY='pravilo_seen_build_v1';
  let latestBuild=null;
  const $=id=>document.getElementById(id);
  function toast(text){let t=$('appHelpToast');if(!t){t=document.createElement('div');t.id='appHelpToast';t.className='toast';document.body.appendChild(t);}t.textContent=text;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2000);}
  function ensureGuide(){
    if($('guideFeatureOverlay'))return;
    const o=document.createElement('div');o.id='guideFeatureOverlay';o.className='featureOverlay';o.innerHTML=`<div class="featureSheet"><div class="featureGrabber"></div><div class="featureSheetHead"><div><div class="featureKicker">Короткая инструкция</div><div class="featureTitle">Как устроено «Правило»</div><div class="featureLead">Норма задаёт ритм, выполненное списывается, а специальные режимы помогают молитве, чтению и медитации.</div></div><button class="featureClose" type="button" data-guide-close>✕</button></div><div class="guideCards"><div class="guideCard"><div class="guideNum">一</div><div class="guideTitle">Обычная норма</div><div class="guideText">Задай объём и период. Невыполненный остаток сохраняется, если не включён режим «с чистого дня».</div></div><div class="guideCard"><div class="guideNum">二</div><div class="guideTitle">Режим книги</div><div class="guideText">Укажи книгу, текущую страницу и срок. На карточке всегда показывается именно объём на сегодня.</div></div><div class="guideCard"><div class="guideNum">三</div><div class="guideTitle">Практика</div><div class="guideText">Молитвенный счётчик работает по касанию, медитация — как отдельный таймер с темой и заметкой.</div></div><div class="guideCard"><div class="guideNum">四</div><div class="guideTitle">История и Путь</div><div class="guideText">Тестовые записи можно удалить; заметки чтения и медитации остаются рядом с соответствующими событиями.</div></div><div class="guideCard"><div class="guideNum">五</div><div class="guideTitle">Резервная копия</div><div class="guideText">Экспорт сохраняет локальные данные приложения. Импорт возвращает их на устройство.</div></div></div><div class="featureActions"><button class="button" type="button" id="guideWelcome">Показать приветствие</button><button class="button primary" type="button" data-guide-close>Понятно</button></div></div>`;document.body.appendChild(o);
    o.addEventListener('click',e=>{if(e.target===o)o.classList.remove('show');});o.querySelectorAll('[data-guide-close]').forEach(b=>b.addEventListener('click',()=>o.classList.remove('show')));$('guideWelcome').addEventListener('click',()=>{o.classList.remove('show');window.showPraviloOnboarding?.(true);});
  }
  function openGuide(){ensureGuide();$('guideFeatureOverlay')?.classList.add('show');}
  function injectSettings(){
    const sheet=$('settingsOverlay')?.querySelector('.sheet');if(!sheet||$('featureSettingsRow'))return;const destructive=$('clearHistory')?.closest('.sheetActions');const row=document.createElement('div');row.id='featureSettingsRow';row.className='featureSettingsRow';row.innerHTML=`<button class="button" type="button" id="openGuideBtn">Как пользоваться</button><button class="button" type="button" id="checkUpdateBtn">Проверить обновление</button>`;(destructive||sheet).insertAdjacentElement(destructive?'beforebegin':'beforeend',row);$('openGuideBtn').addEventListener('click',openGuide);$('checkUpdateBtn').addEventListener('click',()=>checkForUpdate(true));
  }
  function ensureBanner(){if($('updateBanner'))return;const b=document.createElement('div');b.id='updateBanner';b.className='updateBanner';b.innerHTML=`<div><div class="updateKicker">Новая версия</div><div class="updateTitle">Есть обновление «Правила»</div></div><button class="updateButton" type="button" id="updateNowBtn">Обновить</button>`;document.querySelector('.tabs')?.insertAdjacentElement('afterend',b);$('updateNowBtn').addEventListener('click',applyUpdate);}
  async function remoteBuild(){try{const r=await fetch(`sw.js?check=${Date.now()}`,{cache:'no-store'});const t=await r.text();return t.match(/(?:const CACHE=['"]([^'"]+)['"]|const APP_VERSION=['"]([^'"]+)['"])/)?.slice(1).find(Boolean)||null;}catch(e){return null;}}
  async function checkForUpdate(manual=false){ensureBanner();const build=await remoteBuild();if(!build){if(manual)toast('Не удалось проверить обновление');return;}latestBuild=build;const seen=localStorage.getItem(SEEN_BUILD_KEY);if(!seen){localStorage.setItem(SEEN_BUILD_KEY,build);if(manual)toast('Установлена актуальная версия');return;}if(build!==seen){$('updateBanner').classList.add('show');if(manual)toast('Найдена новая версия');}else{$('updateBanner').classList.remove('show');if(manual)toast('Обновлений нет');}}
  async function applyUpdate(){const b=$('updateNowBtn');if(b){b.disabled=true;b.textContent='Обновляю…';}if(latestBuild)localStorage.setItem(SEEN_BUILD_KEY,latestBuild);try{const reg=await navigator.serviceWorker?.getRegistration();await reg?.update();if(reg?.waiting)reg.waiting.postMessage({type:'SKIP_WAITING'});}catch(e){}setTimeout(()=>location.reload(),500);}
  window.praviloOpenGuide=openGuide;
  window.praviloCheckUpdate=()=>checkForUpdate(true);
  function init(){ensureGuide();injectSettings();ensureBanner();checkForUpdate(false);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
