(()=>{
  'use strict';
  const LEGACY_REMINDERS_KEY='pravilo_reminders_v1';
  const APP_VERSION='1.0.1';
  const APP_AUTHOR='Алексей Возняк';
  const $=id=>document.getElementById(id);

  function openOverlay(id){$(id)?.classList.add('show');}
  function closeOverlay(id){$(id)?.classList.remove('show');}
  function click(id){$(id)?.click();}
  function reminderCount(){if(Array.isArray(window.state?.reminders))return state.reminders.filter(r=>r.enabled!==false).length;try{const legacy=JSON.parse(localStorage.getItem(LEGACY_REMINDERS_KEY)||'[]');return Array.isArray(legacy)?legacy.filter(r=>r.enabled!==false).length:0;}catch(e){return 0;}}
  function createSection(id,title,lead,bodyHtml){if($(id))return $(id);const overlay=document.createElement('div');overlay.id=id;overlay.className='overlay settingsSectionOverlay';overlay.innerHTML=`<div class="sheet settingsSectionSheet"><div class="grabber"></div><div class="sheetHeader"><div class="sheetTitle">${title}</div><button class="settingsBack" type="button" data-settings-back>Назад</button></div><div class="settingsSectionLead">${lead}</div><div class="settingsSectionBody">${bodyHtml}</div></div>`;document.body.appendChild(overlay);overlay.querySelector('[data-settings-back]').addEventListener('click',()=>closeOverlay(id));overlay.addEventListener('click',event=>{if(event.target===overlay)closeOverlay(id);});return overlay;}

  function buildDataSection(){
    const overlay=createSection('settingsDataOverlay','Данные','Резервные копии, экспорт и локальное хранение.',`
      <div class="settingsCard"><strong>Данные хранятся на этом устройстве</strong><div class="settingsCardText">Экспорт JSON — внешняя резервная копия. Локальная копия IndexedDB помогает при работе офлайн.</div></div>
      <div class="settingsActionGrid"><button class="button" type="button" id="settingsExportData">Экспорт данных</button><button class="button" type="button" id="settingsImportData">Импорт данных</button><button class="button" type="button" id="settingsExportNotes">Выгрузить заметки</button><button class="button" type="button" id="settingsRefreshOffline">Обновить локальную копию</button></div>
      <div class="settingsStatus" id="settingsOfflineStatus">Проверяю локальное хранение…</div>
      <details class="settingsDanger"><summary>Опасные действия</summary><div class="settingsDangerBody"><button class="button danger" type="button" id="settingsClearHistory">Очистить историю</button><button class="button danger" type="button" id="settingsResetAll">Сбросить всё</button></div></details>`);
    $('settingsExportData').addEventListener('click',()=>click('exportBtn'));$('settingsImportData').addEventListener('click',()=>click('importBtn'));$('settingsExportNotes').addEventListener('click',()=>window.praviloExportNotes?.()||click('exportNotesBtn'));$('settingsRefreshOffline').addEventListener('click',async()=>{if(window.praviloRefreshOfflineBackup)await window.praviloRefreshOfflineBackup();else click('refreshOfflineBackup');await refreshOfflineStatus();});$('settingsClearHistory').addEventListener('click',()=>click('clearHistory'));$('settingsResetAll').addEventListener('click',()=>click('resetAll'));return overlay;
  }

  function buildAppSection(){
    const overlay=createSection('settingsAppOverlay','Приложение','Звуки, обновления, установка и сведения о приложении.',`
      <div class="settingsActionStack"><button class="button" type="button" id="settingsOpenGuide">Как пользоваться</button><button class="button" type="button" id="settingsCheckUpdate">Проверить обновление</button><button class="button" type="button" id="settingsInstallHelp">Установка на телефон</button></div>
      <div class="settingsCard settingsAudioCard" id="settingsAudioCard">
        <div class="settingsAudioHead"><div><strong>Звуки практики</strong><div class="settingsCardText">Сигналы на 10 и 100 молитв и колокол медитации.</div></div><button class="switch" type="button" id="settingsAudioToggle" aria-label="Звуки практики" aria-pressed="true"></button></div>
        <label class="settingsAudioVolume"><span>Общая громкость</span><input type="range" id="settingsAudioVolume" min="15" max="100" step="5" value="100"><b id="settingsAudioVolumeValue">100%</b></label>
        <div class="settingsAudioPreview"><button class="button" type="button" data-audio-preview="prayerTen">10</button><button class="button" type="button" data-audio-preview="prayerHundred">100</button><button class="button" type="button" data-audio-preview="meditationBell">Медитация</button></div>
      </div>
      <div class="settingsCard settingsAboutCard"><div class="settingsAboutTop"><div class="settingsAboutName">Правило</div><div class="settingsAboutVersion">версия ${APP_VERSION}</div></div><div class="settingsAboutAuthor">Автор — ${APP_AUTHOR} · 2026</div><div class="settingsCardText">Личное локальное PWA для молитвы, чтения, медитации и собственного ритма. Основные данные остаются на устройстве; интернет нужен только для обновления приложения.</div></div>`);
    $('settingsOpenGuide').addEventListener('click',()=>window.praviloOpenGuide?.()||click('openGuideBtn'));$('settingsCheckUpdate').addEventListener('click',()=>window.praviloCheckUpdate?.()||click('checkUpdateBtn'));$('settingsInstallHelp').addEventListener('click',()=>window.praviloOpenInstallHelp?.()||click('installSettingsBtn'));$('settingsAudioToggle').addEventListener('click',()=>{const audio=window.PraviloAudio;if(!audio)return;const current=audio.getSettings();audio.setSettings({enabled:!current.enabled});syncAudioSettings();});$('settingsAudioVolume').addEventListener('input',event=>{const audio=window.PraviloAudio;if(!audio)return;audio.setSettings({volume:Number(event.target.value)/100});syncAudioSettings();});overlay.querySelectorAll('[data-audio-preview]').forEach(button=>button.addEventListener('click',()=>{void window.PraviloAudio?.play(button.dataset.audioPreview,{preview:true,direct:true});}));syncAudioSettings();return overlay;
  }

  function syncAudioSettings(){const audio=window.PraviloAudio,toggle=$('settingsAudioToggle'),range=$('settingsAudioVolume'),value=$('settingsAudioVolumeValue'),card=$('settingsAudioCard');if(!audio||!toggle||!range||!value)return;const settings=audio.getSettings(),percent=Math.round(settings.volume*100);toggle.classList.toggle('on',settings.enabled);toggle.setAttribute('aria-pressed',settings.enabled?'true':'false');range.value=String(percent);value.textContent=`${percent}%`;card?.classList.toggle('audioMuted',!settings.enabled);}
  function hideLegacySettingsContent(sheet,hub){[...sheet.children].forEach(node=>{if(node===hub||node.classList.contains('grabber')||node.classList.contains('sheetHeader'))return;node.classList.add('settingsHubSource');});}
  function buildHub(){const sheet=$('settingsOverlay')?.querySelector('.sheet');if(!sheet||$('settingsHub'))return;buildDataSection();buildAppSection();const hub=document.createElement('div');hub.id='settingsHub';hub.className='settingsHub';hub.innerHTML=`<button class="settingsHubRow" id="settingsHubReminders" type="button"><span class="settingsHubIcon"><img src="images/settings-reminders.webp" alt=""></span><span><span class="settingsHubTitle">Напоминания</span><span class="settingsHubSub" id="settingsHubReminderSub"></span></span><span class="settingsHubArrow">›</span></button><button class="settingsHubRow" id="settingsHubData" type="button"><span class="settingsHubIcon"><img src="images/settings-data.webp" alt=""></span><span><span class="settingsHubTitle">Данные</span><span class="settingsHubSub">копия · экспорт · офлайн</span></span><span class="settingsHubArrow">›</span></button><button class="settingsHubRow" id="settingsHubApp" type="button"><span class="settingsHubIcon"><img src="images/settings-app.webp" alt=""></span><span><span class="settingsHubTitle">Приложение</span><span class="settingsHubSub">звуки · помощь · версия 1.0</span></span><span class="settingsHubArrow">›</span></button>`;sheet.querySelector('.sheetHeader')?.insertAdjacentElement('afterend',hub);hideLegacySettingsContent(sheet,hub);$('settingsHubReminders').addEventListener('click',()=>{if(window.praviloOpenReminders)window.praviloOpenReminders();else if($('openReminders'))click('openReminders');else openOverlay('remindersOverlay');});$('settingsHubData').addEventListener('click',async()=>{openOverlay('settingsDataOverlay');await refreshOfflineStatus();});$('settingsHubApp').addEventListener('click',()=>{syncAudioSettings();openOverlay('settingsAppOverlay');});updateReminderStatus();}
  function updateReminderStatus(){const count=reminderCount(),el=$('settingsHubReminderSub');if(el)el.textContent=count?`${count} ${count===1?'активное':'активных'}`:'не настроены';}
  async function refreshOfflineStatus(){const el=$('settingsOfflineStatus');if(!el)return;if(!window.praviloOfflineStatus){el.textContent='Локальная копия подготавливается.';return;}const status=await window.praviloOfflineStatus();el.textContent=status.text;}
  function init(){buildHub();updateReminderStatus();window.addEventListener('pravilo:reminders-changed',updateReminderStatus);window.addEventListener('pravilo:state-saved',updateReminderStatus);window.addEventListener('pravilo:offline-status',refreshOfflineStatus);window.addEventListener('pravilo:audio-settings',syncAudioSettings);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
